/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DoctorsOffice { 
    officeName?: string;
    address?: string;
    labEquipment?: string;
    doctorSsn?: string;
    staffSsn?: string;
    nurseSsn?: string;
}

