/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsuranceCompany { 
    companyName?: string;
    contactNumber?: string;
    address?: string;
    email?: string;
    website?: string;
}

