/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MedicalAppointmentId } from './medicalAppointmentId';


export interface MedicalAppointment { 
    id?: MedicalAppointmentId;
    reason?: string;
    officeName?: string;
}

