/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentHistoryId } from './paymentHistoryId';


export interface PaymentHistory { 
    id?: PaymentHistoryId;
    amount?: number;
    officeName?: string;
}

