/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PharmacyId } from './pharmacyId';


export interface Pharmacy { 
    id?: PharmacyId;
    amount?: number;
    address?: string;
}

