/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrescriptionId } from './prescriptionId';


export interface Prescription { 
    id?: PrescriptionId;
    amount?: number;
    pharmacy?: string;
}

