/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrescriptionId { 
    date?: string;
    medicine?: string;
    dssn?: string;
    pssn?: string;
}

