export * from './doctorController.service';
import { DoctorControllerService } from './doctorController.service';
export * from './doctorsOfficeController.service';
import { DoctorsOfficeControllerService } from './doctorsOfficeController.service';
export * from './insuranceCompanyController.service';
import { InsuranceCompanyControllerService } from './insuranceCompanyController.service';
export * from './medicalAppointmentController.service';
import { MedicalAppointmentControllerService } from './medicalAppointmentController.service';
export * from './medicalTestController.service';
import { MedicalTestControllerService } from './medicalTestController.service';
export * from './nurseController.service';
import { NurseControllerService } from './nurseController.service';
export * from './officeStaffController.service';
import { OfficeStaffControllerService } from './officeStaffController.service';
export * from './patientController.service';
import { PatientControllerService } from './patientController.service';
export * from './paymentHistoryController.service';
import { PaymentHistoryControllerService } from './paymentHistoryController.service';
export * from './pharmacyController.service';
import { PharmacyControllerService } from './pharmacyController.service';
export * from './prescriptionController.service';
import { PrescriptionControllerService } from './prescriptionController.service';
export const APIS = [DoctorControllerService, DoctorsOfficeControllerService, InsuranceCompanyControllerService, MedicalAppointmentControllerService, MedicalTestControllerService, NurseControllerService, OfficeStaffControllerService, PatientControllerService, PaymentHistoryControllerService, PharmacyControllerService, PrescriptionControllerService];
